FROM node:20-alpine AS builder
WORKDIR /app
COPY resq/package*.json ./
RUN npm ci
COPY resq/ .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY server/package*.json ./
RUN npm ci --only=production
COPY server/ .
COPY --from=builder /app/dist ./public
ENV PORT=8080
EXPOSE 8080
CMD ["node", "index.js"]